// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace FoodPal.Providers.DataAccess.Migrations
{
    [DbContext(typeof(ProvidersContext))]
    partial class ProvidersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FoodPal.Providers.DomainModels.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.CatalogueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CatalogueId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogueItems");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.CatalogueItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CatalogueItemCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 637, DateTimeKind.Local).AddTicks(9273),
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 637, DateTimeKind.Local).AddTicks(9894),
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 637, DateTimeKind.Local).AddTicks(9907),
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 637, DateTimeKind.Local).AddTicks(9910),
                            Name = "Aperitives"
                        });
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.ProviderCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProviderCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 632, DateTimeKind.Local).AddTicks(9078),
                            Name = "mediterranean Cuisine"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 636, DateTimeKind.Local).AddTicks(5298),
                            Name = "Traditional Romanian Cuisine"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 636, DateTimeKind.Local).AddTicks(5336),
                            Name = "Japanese Cuisine"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 2, 13, 17, 14, 36, 636, DateTimeKind.Local).AddTicks(5342),
                            Name = "Thai Cuisine"
                        });
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.Catalogue", b =>
                {
                    b.HasOne("FoodPal.Providers.DomainModels.Provider", "Provider")
                        .WithOne("Catalogue")
                        .HasForeignKey("FoodPal.Providers.DomainModels.Catalogue", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.CatalogueItem", b =>
                {
                    b.HasOne("FoodPal.Providers.DomainModels.Catalogue", "Catalogue")
                        .WithMany("Items")
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodPal.Providers.DomainModels.CatalogueItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogue");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.Provider", b =>
                {
                    b.HasOne("FoodPal.Providers.DomainModels.ProviderCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.Catalogue", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModels.Provider", b =>
                {
                    b.Navigation("Catalogue");
                });
#pragma warning restore 612, 618
        }
    }
}
